# Generated by Django 6.0.2 on 2026-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyuser',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
