# Generated by Django 6.0.2 on 2026-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_propertyuser_email_propertyuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bhk',
            field=models.CharField(blank=True, choices=[('1RK', '1 RK'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('5BHK+', '5 BHK+')], max_length=20, null=True),
        ),
    ]
