# Generated by Django 6.0.2 on 2026-03-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_property_bhk'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyuser',
            name='is_click',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='propertyuser',
            name='is_search',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
