# Generated by Django 6.0.3 on 2026-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_propertyuser_is_click_propertyuser_is_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=255, null=True)),
                ('service_hrs', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
