# Generated by Django 6.0.3 on 2026-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_propertyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimages',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
